# section 1
global: 
  scrape_interval: 5s
  external_labels:
    monitor: 'node-monitor'  
  
# section 2  
scrape_configs: 
  - job_name: prometheus
    static_configs: 
      - targets: 
          - "localhost:9090"

 - job_name: node-exporter
    static_configs:
      - targets:
          - "10.130.128.175:9100"
          - "10.130.128.242:9100"
